pipeline {
    agent any

    stages {
 
        stage('Run Node.js') {
            steps {
                script {
                    sh """
                    cd pipeline-2
                    node app.js
                    """
                }
            }
        }

        stage('Run Go') {
            steps {
                script {
                    sh """
                    cd pipeline-2
                    go run main.go
                    """
                }
            }
        }

        stage('Run Java') {
            steps {
                script {
                    sh """
                    cd pipeline-2
                    javac HelloJenkins.java && java HelloJenkins
                    """
                }
            }
        }
    }
}
