pipeline {
    agent any

    stages {

        stage('Run Node.js') {
            steps {
                script {
                    sh 'node app.js'
                }
            }
        }

        stage('Run Go') {
            steps {
                script {
                    sh 'go run main.go'
                }
            }
        }

        stage('Run Java') {
            steps {
                script {
                    sh 'javac HelloJenkins.java && java HelloJenkins'
                }
            }
        }
    }
}
