pipeline {
    agent any
    
    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    sh """
                    cd pipeline-1
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install pandas scikit-learn
                    """
                }
            }
        }

        stage('Train Model') {
            steps {
                script {
                    sh """
                    cd pipeline-1
                    . venv/bin/activate
                    python model.py
                    """
                }
            }
        }
    }
}